version: '3'
services:
  builder:
    image: mikebell/eleventy:0.8.3
    command: > 
      ash -c "npm install &&
      eleventy"
    volumes:
      - .:/usr/src
  serve:
    image: mikebell/eleventy:0.8.3
    command: > 
      ash -c "npm install &&
      eleventy --serve"
    volumes:
      - .:/usr/src