[build]
  publish = "_site"
  command = "eleventy"

[build.environment]
  NLC_GA_UA = "UA-69921843-12"

[context.production.environment]
  NLC_GA_UA = "UA-69921843-11"


# REDIRECT and HEADERS examples

# Redirect rule example
# For more information see:- https://www.netlify.com/docs/netlify-toml-reference/

[[redirects]]
#  from = "/*"
#  to = "/blog/:splat"

# The default HTTP status code is 301, but you can define a different one e.g.
# status = 302

# These rules will change if you change your site’s custom domains or HTTPS settings

# Redirect domain aliases to primary domain
from = "https://nationalleadership.gov.uk/*"
to = "https://www.nationalleadership.gov.uk/:splat"
status = 301
force = true

from = "https://www.nationalleadershipcentre.co.uk/*"
to = "https://www.nationalleadership.gov.uk/:splat"
status = 301
force = true

# Headers rule example
# For more information see:- https://www.netlify.com/docs/netlify-toml-reference/

#[[headers]]
#   Define which paths this specific [[headers]] block will cover.
#   for = "/*"

#[headers.values]
#   X-Frame-Options = "DENY"
#   X-XSS-Protection = "1; mode=block"
#   Content-Security-Policy = "frame-ancestors https://www.facebook.com"

# Redirects and headers are GLOBAL for all builds – they do not get scoped to
# contexts no matter where you define them in the file.
# For context-specific rules, use _headers or _redirects files, which are
# applied on a PER-DEPLOY basis.
